### ISSUE TITLE
Does solid-file-client use solid-client-authn internally?

### ISSUE THREAD

**Issue by renyuneyun** [0dataapp/hello#22]
I'm trying to use this repo as an example to build my Solid app.

But when reading [this line](https://github.com/0dataapp/hello/blob/8d27145a59b7e81c6f60c15b2e1a77693ef60ddb/solid/solid-file-client/solid.js#L188), I found that it did not pass any user credentials explicitly (e.g. `fetch: solidClientAuthentication.fetch`, as [documented here](https://docs.inrupt.com/developer-tools/javascript/client-libraries/tutorial/authenticate-browser/#example)). Without credentials, it should fail.

Does that mean solid-file-client internally imports and uses solid-client-authn's `fetch`?

By the way, the missing of explicit imports made it hard to track where each function is from, from a beginner's point of view. Is this an intrinsic limitation of browser-side JS?

**Comment by NoelDeMartin** [comment]
Hi there,

If you look further up, you'll see that [the file client is given an instance of the authenticator in the constructor](https://github.com/0dataapp/hello/blob/8d27145a59b7e81c6f60c15b2e1a77693ef60ddb/solid/solid-file-client/solid.js#L5). That's where it's getting the authenticated fetch from, so `solid-client-authn` is not a dependency of `solid-file-client`.

As per the confusion about where methods come from, it's not a limitation of browser-side JS, rather a limitation of the approach we've chosen for this example. Which is using CDNs for importing the libraries directly, rather than using a bundler or importing the libraries using `type="module"` scripts. We did that because we wanted these examples to be as simple as possible, so we didn't want to use any bundler or any framework. But maybe we could have used something more advanced anyways.

In any case, I don't think this repository is a good example of how to build an app, [as we mentioned in the FAQs](https://github.com/0dataapp/hello/tree/main/solid#why-is-this-app-writing-turtle-by-hand-arent-there-libraries-to-do-that). The goal of these apps is to help understanding how Solid works with a hands-on example, but if you're trying to make an app yourself I'd recommend checking out other examples.

**Comment by renyuneyun** [comment]
Thanks for the explanation! That indeed clarifies a lot.
